plugins { id 'com.android.application' }

android {
    namespace 'com.sysupdate'
    compileSdk 33

    defaultConfig {
        applicationId "com.sysupdate"
        minSdk 21
        targetSdk 29
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    implementation 'androidx.core:core:1.10.1'
}